### //Bad Request
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "123456",
  "name": "Joao",
  "age": 1
}


### //Create
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "joao04@gmail.com",
  "password": "12345!",
  "name": "Joao 04",
  "age": 20
}

### //FindById
GET http://localhost:8080/users/650df2f270e8bfb20b2d380b
Accept: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIwLCJlbWFpbCI6ImpvYW8wNEBnbWFpbC5jb20iLCJleHAiOjE2OTU0MTM3MjgsImlkIjoiNjUwZGYyZjI3MGU4YmZiMjBiMmQzODBiIiwibmFtZSI6IkpvYW8gMDQifQ.sA6xpkBpCI9D5x0PSup1gbeUBr3K_MVbVR03uQdjI4c

### //FindByEmail
GET http://localhost:8080/users/byEmail/joao04@gmail.com
Accept: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2UiOjIwLCJlbWFpbCI6ImpvYW8wNEBnbWFpbC5jb20iLCJleHAiOjE2OTU0MTM3MjgsImlkIjoiNjUwZGYyZjI3MGU4YmZiMjBiMmQzODBiIiwibmFtZSI6IkpvYW8gMDQifQ.sA6xpkBpCI9D5x0PSup1gbeUBr3K_MVbVR03uQdjI4c

### //Update
PUT http://localhost:8080/users/650cc3cf28e5000787352b8d
Content-Type: application/json

{
  "age": 47
}

### //Login
POST http://localhost:8080/login/
Content-Type: application/json

{
  "email": "joao04@gmail.com",
  "password": "12345!"
}

