GET http://localhost:8080/users/1

### //Bad Request
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "123456",
  "name": "Joao",
  "age": 1
}


### //Ok
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "arilson@gmail.com",
  "password": "12345!",
  "name": "Arilson",
  "age": 1
}

### //FindById

GET http://localhost:8080/users/650ce5e913e3a10ba38dad5e

### //FindByEmail

GET http://localhost:8080/users/byEmail/arilson@gmail.com

### //Update

PUT http://localhost:8080/users/650cc3cf28e5000787352b8d
Content-Type: application/json

{
  "age": 47
}

### //Delete

DELETE http://localhost:8080/users/650ce5e913e3a10ba38dad5e

