# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@develop
      env:
        GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secretes.SONAR_TOKEN }}